#!/usr/bin/env python3
"""Generates AAE's keyboard layouts, one per language Android has.

Each layout is AAE's PC keyboard (base.kcm: every scan code mapped as a PC
keyboard's, so Meta, Escape, Home and End are keys) with one language's
characters and key changes from Android's own layouts (aosp/, from Android's
InputDevices app, Apache License 2.0).

Writes the helper's res/raw/aae_*.kcm and res/xml/keyboard_layouts.xml, and
the core's table of them, crates/aae-core/src/keyboard_layouts_table.rs.

    python3 android/helper/layouts/generate.py
"""

import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent
RAW = HERE.parent / "src/main/res/raw"
XML = HERE.parent / "src/main/res/xml/keyboard_layouts.xml"
TABLE = ROOT / "crates/aae-core/src/keyboard_layouts_table.rs"

# Name, label, and the language tags it's chosen for, first the most usual.
LAYOUTS = [
    ("english_us", "English (US)", ["en-US", "en"]),
    ("english_uk", "English (UK)", ["en-GB", "en-IE"]),
    ("english_us_intl", "English (US, international)", []),
    ("english_india", "English (India)", ["en-IN"]),
    ("english_us_colemak", "English (US, Colemak)", []),
    ("english_us_dvorak", "English (US, Dvorak)", []),
    ("english_us_workman", "English (US, Workman)", []),
    ("german", "German", ["de-DE", "de-AT", "de"]),
    ("swiss_german", "German (Switzerland)", ["de-CH"]),
    ("french", "French", ["fr-FR", "fr"]),
    ("belgian", "French (Belgium)", ["fr-BE", "nl-BE"]),
    ("french_ca", "French (Canada)", ["fr-CA"]),
    ("swiss_french", "French (Switzerland)", ["fr-CH"]),
    ("italian", "Italian", ["it"]),
    ("spanish", "Spanish", ["es-ES", "es"]),
    ("spanish_latin", "Spanish (Latin America)", ["es-419", "es-MX", "es-AR", "es-CO", "es-CL"]),
    ("portuguese", "Portuguese", ["pt-PT", "pt"]),
    ("brazilian", "Portuguese (Brazil)", ["pt-BR"]),
    ("swedish", "Swedish", ["sv"]),
    ("norwegian", "Norwegian", ["nb", "nn", "no"]),
    ("danish", "Danish", ["da"]),
    ("finnish", "Finnish", ["fi"]),
    ("icelandic", "Icelandic", ["is"]),
    ("estonian", "Estonian", ["et"]),
    ("latvian_qwerty", "Latvian", ["lv"]),
    ("lithuanian", "Lithuanian", ["lt"]),
    ("polish", "Polish", ["pl"]),
    ("czech", "Czech", ["cs"]),
    ("czech_qwerty", "Czech (QWERTY)", []),
    ("slovak", "Slovak", ["sk"]),
    ("hungarian", "Hungarian", ["hu"]),
    ("romanian", "Romanian", ["ro"]),
    ("croatian_and_slovenian", "Croatian and Slovenian", ["hr", "sl", "bs"]),
    ("serbian_and_montenegrin_latin", "Serbian and Montenegrin (Latin)", ["sr-Latn", "cnr"]),
    ("serbian_and_montenegrin_cyrillic", "Serbian and Montenegrin (Cyrillic)", ["sr"]),
    ("bulgarian", "Bulgarian", ["bg"]),
    ("bulgarian_phonetic", "Bulgarian (phonetic)", []),
    ("russian", "Russian", ["ru"]),
    ("russian_mac", "Russian (Mac)", []),
    ("ukrainian", "Ukrainian", ["uk"]),
    ("belarusian", "Belarusian", ["be"]),
    ("greek", "Greek", ["el"]),
    ("hebrew", "Hebrew", ["he", "iw"]),
    ("arabic", "Arabic", ["ar"]),
    ("persian", "Persian", ["fa"]),
    ("turkish", "Turkish", ["tr"]),
    ("turkish_f", "Turkish (F)", []),
    ("georgian", "Georgian", ["ka"]),
    ("azerbaijani", "Azerbaijani", ["az"]),
    ("mongolian", "Mongolian", ["mn"]),
    ("thai_kedmanee", "Thai (Kedmanee)", ["th"]),
    ("thai_pattachote", "Thai (Pattachote)", []),
]

LICENCE = """\
# Generated by android/helper/layouts/generate.py: don't edit. AAE's PC
# keyboard (layouts/base.kcm) with the characters and key changes of
# Android's {source} (layouts/aosp/), which carries this notice:
#
# Copyright (C) The Android Open Source Project
# Licensed under the Apache License, Version 2.0. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0. Distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
"""


def parse(text):
    """The map key lines, by scan code, and the key blocks, by key name, in order."""
    maps = {}
    keys = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        m = re.match(r"map key (\d+) (\S+)", line)
        if m:
            maps[int(m.group(1))] = m.group(2)
        m = re.match(r"key (\S+) \{", line)
        if m:
            block = [lines[i]]
            while not lines[i].strip().startswith("}"):
                i += 1
                block.append(lines[i])
            keys[m.group(1)] = "\n".join(block)
        i += 1
    return maps, keys


def file_name(name):
    # English (US) keeps the name devices already have selected.
    return "aae_full_keyboard" if name == "english_us" else f"aae_{name}"


def descriptor_name(name):
    return "aae_full" if name == "english_us" else f"aae_{name}"


def main():
    base_maps, base_keys = parse((HERE / "base.kcm").read_text())
    entries = []
    rows = []
    for name, label, languages in LAYOUTS:
        source = f"keyboard_layout_{name}.kcm"
        maps, keys = parse((HERE / "aosp" / source).read_text())
        merged_maps = dict(base_maps)
        merged_maps.update(maps)
        merged_keys = dict(keys)
        for key, block in base_keys.items():
            merged_keys.setdefault(key, block)
        out = [LICENCE.format(source=source), "type OVERLAY", ""]
        out += [f"map key {code} {key}" for code, key in sorted(merged_maps.items())]
        out.append("")
        for block in merged_keys.values():
            out += [block, ""]
        (RAW / f"{file_name(name)}.kcm").write_text("\n".join(out))
        entries.append(
            f'    <keyboard-layout\n'
            f'        android:name="{descriptor_name(name)}"\n'
            f'        android:keyboardLayout="@raw/{file_name(name)}"\n'
            f'        android:label="AAE: {label}" />'
        )
        tags = ", ".join(f'"{t}"' for t in languages)
        rows.append(
            f"    Layout {{\n"
            f'        name: "{name}",\n'
            f'        label: "{label}",\n'
            f"        languages: &[{tags}],\n"
            f'        descriptor: "{descriptor_name(name)}",\n'
            f'        kcm: include_str!("../../../android/helper/src/main/res/raw/{file_name(name)}.kcm"),\n'
            f"    }},"
        )
    XML.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by android/helper/layouts/generate.py: don't edit. -->\n"
        '<keyboard-layouts xmlns:android="http://schemas.android.com/apk/res/android">\n'
        + "\n".join(entries)
        + "\n</keyboard-layouts>\n"
    )
    TABLE.write_text(
        "// Generated by android/helper/layouts/generate.py: don't edit.\n\n"
        "use crate::keyboard_layouts::Layout;\n\n"
        "/// AAE's keyboard layouts, in the helper, English (US) first.\n"
        "pub const LAYOUTS: &[Layout] = &[\n" + "\n".join(rows) + "\n];\n"
    )
    print(f"Wrote {len(LAYOUTS)} layouts.")


if __name__ == "__main__":
    main()
