// swift-tools-version: 6.0
// The AAE Mac app. Build it with build.sh, which builds the Rust core first and
// generates the Swift bindings this package compiles against.

import Foundation
import PackageDescription

let repoRoot = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().path
let rustLibDir = ProcessInfo.processInfo.environment["AAE_RUST_LIB_DIR"] ?? "\(repoRoot)/target/release"

let package = Package(
    name: "AAE",
    platforms: [.macOS(.v13)],
    targets: [
        // The C declarations of the Rust core's functions, generated by UniFFI.
        .target(name: "aae_ffiFFI", path: "Sources/aae_ffiFFI"),
        .executableTarget(
            name: "AAE",
            dependencies: ["aae_ffiFFI"],
            path: "Sources/AAE",
            swiftSettings: [.swiftLanguageMode(.v5)],
            linkerSettings: [
                .unsafeFlags(["-L", rustLibDir]),
                .linkedLibrary("aae_ffi"),
                .linkedLibrary("c++"),
                .linkedLibrary("iconv"),
                .linkedFramework("AppKit"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("IOKit"),
                .linkedFramework("ApplicationServices"),
                .linkedFramework("Carbon"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),
    ]
)
